# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    name: ${{ matrix.os }} - ${{ matrix.node-version }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x, 22.x, 24.x]
        os: ["windows-latest", "ubuntu-latest", "macos-latest"]
        exclude:
          - node-version: 20.x
            os: windows-latest
          - node-version: 22.x
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache dependencies and build info
      uses: actions/cache@v4
      with:
        path: |
          node_modules
          dist/.tsbuildinfo
        key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('package-lock.json') }}
    - run: npm install --prefer-offline --no-audit  --no-fund
    - run: npm test
permissions:
  contents: read
